map_data = [1 2 3 2 4 8 9 7 10 10 8 8 9 9 10 1 3 3 2 2]'; 

groups = [ 1 1; ...
           1 1; ...
           1 1; ...
           1 1; ...
           1 1; ...
           1 2; ...
           1 2; ...
           1 2; ...
           1 2; ...
           1 2; ...
           2 1; ...
           2 1; ...
           2 1; ...
           2 1; ...
           2 1; ...
           2 2; ...
           2 2; ...
           2 2; ...
           2 2; ...
           2 2 ];
    
anova_data = struct('TBI', {}, 'Training', {}, 'data', {});
for r = 1:length(map_data)
    anova_data(end+1) = struct('TBI', groups(r, 1), 'Training', groups(r, 2), 'data', map_data(r));
end

dependent_variable = [anova_data.data];
independent_variables = {[anova_data.TBI] [anova_data.Training]};

[p, table, stats] = anovan(dependent_variable, independent_variables, 'display', 'off', 'model', 'full', ...
    'varnames', {'TBI', 'Training'});

% 
% group_means = [nanmean(map_data(1:5)) nanmean(map_data(6:10)) nanmean(map_data(11:15)) nanmean(map_data(16:20))];
% group_err = [   (nanstd(map_data(1:5))   / sqrt(5)) ...
%                 (nanstd(map_data(6:10))  / sqrt(5)) ...
%                 (nanstd(map_data(11:15)) / sqrt(5)) ...
%                 (nanstd(map_data(16:20)) / sqrt(5)) ];
%             
%             
% 
% 
% figure;
% errorbar(1:4, group_means, group_err, group_err, 'LineStyle', 'none', 'Marker', 'o', 'MarkerFaceColor', 'k', 'Color', 'k');
% set(gca, 'XTick', 1:4);
% set(gca, 'XTickLabel', {'Control', 'TBI Only', 'Training Only', 'TBI+Training'});
% set(gca, 'XTickLabelRotation', 15);



